# Generated by Django 4.2.4 on 2023-10-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_heading_posts_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="date",
            new_name="created_at",
        ),
    ]
