# Generated by Django 4.2.4 on 2023-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_date_posts_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(default="", editable=False, max_length=200),
        ),
    ]
