# Generated by Django 4.2.4 on 2023-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_posts_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="slug",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
